var annotated_dup =
[
    [ "cadastrochamado", "classcadastrochamado.html", "classcadastrochamado" ],
    [ "cadastrodispositivo", "classcadastrodispositivo.html", "classcadastrodispositivo" ],
    [ "Cadastropessoa", "classCadastropessoa.html", "classCadastropessoa" ],
    [ "cadastroprioridade", "classcadastroprioridade.html", "classcadastroprioridade" ],
    [ "cadastrostatus", "classcadastrostatus.html", "classcadastrostatus" ],
    [ "cadastrousuario", "classcadastrousuario.html", "classcadastrousuario" ],
    [ "Chamado", "classChamado.html", "classChamado" ],
    [ "conectabanco", "classconectabanco.html", "classconectabanco" ],
    [ "Dispositivo", "classDispositivo.html", "classDispositivo" ],
    [ "gerenciaChamados", "classgerenciaChamados.html", "classgerenciaChamados" ],
    [ "gerenciaDispositivo", "classgerenciaDispositivo.html", "classgerenciaDispositivo" ],
    [ "gerenciaPessoas", "classgerenciaPessoas.html", "classgerenciaPessoas" ],
    [ "GrupoP", "classGrupoP.html", "classGrupoP" ],
    [ "JanelaPrincipal", "classJanelaPrincipal.html", "classJanelaPrincipal" ],
    [ "Login", "classLogin.html", "classLogin" ],
    [ "matrizRACI", "classmatrizRACI.html", "classmatrizRACI" ],
    [ "MRaci", "classMRaci.html", "classMRaci" ],
    [ "novoGrupo", "classnovoGrupo.html", "classnovoGrupo" ],
    [ "pessoa", "classpessoa.html", "classpessoa" ],
    [ "selecionadisp", "classselecionadisp.html", "classselecionadisp" ],
    [ "selecionaequip", "classselecionaequip.html", "classselecionaequip" ],
    [ "Status", "classStatus.html", "classStatus" ],
    [ "tipod", "classtipod.html", "classtipod" ],
    [ "tipoDisp", "classtipoDisp.html", "classtipoDisp" ]
];